name: warden verify

on:
  push:
    branches: [ "main", "release-*" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false
    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    - name: fmt and unit tests
      run: make verify
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Single Cluster
      uses: AbsaOSS/k3d-action@4e8b3239042be1dc0aed6c5eb80c13b18200fc79 #v2.4.0
      with:
        cluster-name: "k3dCluster"
        args: >-
          --agents 1
          --port 80:80@loadbalancer
          --port 443:443@loadbalancer
          --image rancher/k3s:v1.28.6-k3s1
          --wait
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    - name: setup pre-submit envs
      if: github.event_name == 'pull_request'
      run: |
        echo "IMG_DIRECTORY=dev" >> $GITHUB_ENV
        echo "IMG_VERSION=PR-${{ github.event.number }}" >> $GITHUB_ENV
    - name: setup post-submit envs
      if: github.event_name == 'push'
      run: |
        echo "IMG_DIRECTORY=prod" >> $GITHUB_ENV
        echo "IMG_VERSION=${{github.sha}}" >> $GITHUB_ENV
    - name: run test
      run: make verify-on-cluster
    - name: Show Warden Logs
      if: failure()
      run: kubectl logs -l app=warden -n kyma-system --prefix=true;
